#!/bin/sh

export PATH=/bin:/sbin
VMSYSLOGD_TAG=vmsyslogd
VMSYSLOGD_PID=$(ps -cC | awk -v TAG=$VMSYSLOGD_TAG '{if ($3 == TAG) printf $2;}')
ISRUNNING="${VMSYSLOGD_TAG} is running."
ISNOTRUNNING="${VMSYSLOGD_TAG} is not running."

start() {
    echo "Stating ${VMSYSLOGD_TAG} service using init is not supported"
    return 1
}

stop() {
    echo "Stopping ${VMSYSLOGD_TAG} service using init is not supported"
    return 1
}

restart() {
    return $(/bin/localcli system syslog reload > /dev/null 2>&1)
}

usage() {
    echo "Usage: $0 {start|stop|restart|status}"
}

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

case $1 in
    "start")
        if [ -z "${VMSYSLOGD_PID}" ] ; then
            start
        else
            echo "${ISRUNNING}"
        fi
        ;;
    "stop")
        if [ -n "${VMSYSLOGD_PID}" ] ; then
            stop
        else
            echo "${ISNOTRUNNING}"
        fi
        ;;
    "restart")
        restart
        ;;
    "status")
        if [ -n "${VMSYSLOGD_PID}" ] ; then
            echo "${ISRUNNING}"
            exit 0
        else
            echo "${ISNOTRUNNING}"
            exit 3
        fi
        ;;
    *)
        usage
        exit 1
        ;;
esac

exit $?
